spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    click:
      driverClassName: ru.yandex.clickhouse.ClickHouseDriver
      url: jdbc:clickhouse://192.168.68.201:8123/default
      initialSize: 10
      maxActive: 100
      minIdle: 10
      maxWait: 6000
mybatis-plus:
#  typeAliasesPackage: com.benjamin.springbootclickhousestudy.entity
  mapperLocations: classpath:mapper/*.xml
